<?php
require_once("include/Header.php");
require_once("include/function.php");
require_once("config.php");
require_once("class/Product.php");
require_once("data/ProductData.php");
require_once("class/News.php");
require_once("data/NewsData.php");
require_once("class/NewsClass.php");
require_once("data/NewsClassData.php");
require_once("class/SinglePage.php");
require_once("data/SinglePageData.php");
require_once("class/Baoming.php");
require_once("data/BaomingData.php");
require_once("Base.php");
require_once("include/CheckValue.php");
require_once("class/User.php");
require_once("data/UserData.php");
require_once("class/Score.php");
require_once("data/ScoreData.php");

